###
GET http://localhost:3000/post

###
GET http://localhost:3000/post?sender=arbel

###
GET http://localhost:3000/post/4

###
PUT http://localhost:3000/post/2
Content-Type: application/json

{
    "_id": 2,
    "title": "miau",
    "sender": "michal",
    "content": "miau gam lach"
}

###
POST http://localhost:3000/post
Content-Type: application/json

{
    "_id": 2,
    "title": "Hello",
    "sender": "michal",
    "content": "Hello"
}


# comment
###
GET http://localhost:3000/comment

###
GET http://localhost:3000/comment?sender=arbel

###
GET http://localhost:3000/comment/2

###
POST http://localhost:3000/comment
Content-Type: application/json

{
    "_id": 2,
    "id": 1,
    "title": "Hello",
    "content": "Great post!",
    "sender": "Hod"
}

###
PUT http://localhost:3000/comment/23
Content-Type: application/json

{
    "_id": 23,
    "id": 1,
    "title": "Updated",
    "content": "Post upadted",
    "sender": "Hod"
}

###
DELETE http://localhost:3000/comment/1